### PR TITLE
Optimize TRX burning mechanism in transaction

### PR DESCRIPTION
**Pull request by DmytroShalaiev**
This Tron Proposal describes methods for turning off TRX burn mechanism if resources not enough for transaction. This should improve UX and more accurate predicting of transaction costs.

### CODE REVIEW

**Comment by Murphytron** [comment]
> This Tron Proposal describes methods for turning off TRX burn mechanism if resources not enough for transaction. This should improve UX and more accurate predicting of transaction costs.

Hi! DmytroShalaiev, thank you very much for the effort to contribute to java-tron. I can see you have drafted a detailed proposal about a method of transaction fee processing on the TRON network. Just that in TRON community, there is a standard procedure to follow when developers initiate a proposal, before you submit a TIP, you would need to create an issue for discussion. Please refer to here: https://github.com/tronprotocol/tips#to-submit-a-tip.

So would you please move the PR content to an [tip issue](https://github.com/tronprotocol/tips/issues), so that we can welcome developers to discuss about it. Thank you!

**Comment by DmytroShalaiev** [comment]
Thanks, I will do.

**Comment by DmytroShalaiev** [comment]
https://github.com/tronprotocol/tips/issues/537

**Comment by ethan1844** [comment]
Close this issue as it is moved to https://github.com/tronprotocol/tips/issues/537

**Pull request closed without merging**
